add solution to rating and chars_count methods
Yoffic/study pull request #2
Opened 2021-11-07 16:46 UTC by Yoffic

2021-11-09 06:46 UTC, moklidia requested changes

2021-11-09 06:46 UTC, moklidia commented on test/exercise/fp/solution.rb
> +        rating_to_count = array.reduce([]) { |movies, movie| has_many_countries.call(movie) ? movies << movie : movies }
Давай сначала получим массив отфильтрованных по всем параметрам фильмов и будем обрабатывать его дальше.

2021-11-09 06:46 UTC, moklidia commented on test/exercise/fp/solution.rb
> +          .reduce([]) { |rated_movies, movie| has_needed_rating.call(movie) ? rated_movies << movie : rated_movies }
То же самое: сначала отфильтруй через select, а потом уже работай с отфильтрованной коллекцией

2021-11-09 07:17 UTC, Yoffic commented on test/exercise/fp/solution.rb
> +        rating_to_count = array.reduce([]) { |movies, movie| has_many_countries.call(movie) ? movies << movie : movies }
изначально так и сделала, а потом смутило то, что в задании написано использовать map и reduce)

2021-11-10 13:53 UTC, moklidia requested changes

2021-11-10 13:53 UTC, moklidia commented on test/exercise/fp/solution.rb
> +                               .select(&has_positive_rating)
Давай отфильтруем все сразу одним селектом

2021-11-11 07:05 UTC, moklidia approved these changes

2021-11-11 15:37 UTC, merged